version: "3.9"
services:
  reverse-proxy:
    command:
      # Use docker as provider
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable web UI
      - --api
        # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443
      # Create the certificate resolver "le" for Let's Encrypt
      - --certificatesresolvers.myresolver.acme.email=marcusjorgensson@gmail.com
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "443:443"
    volumes:
      # Mount the volume to store the certificates
      - traefik-public-certificates:/certificates
    labels:
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls.certresolver=le
volumes:
  # Create a volume to store the certificates, there is a constraint to make sure
  # Traefik is always deployed to the same Docker node with the same volume containing
  # the HTTPS certificates
  traefik-public-certificates:
