version: "3.9"
services:
  reverse-proxy:
    command: # Need to have all command, since the original is replaced
      # Use docker as provider
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable web UI
      - --api
      # More verbose log messages
      - --log.level=DEBUG

  backend:
    volumes:
      # Live mount code to get instant feedback
      - ./app/app:/app
