version: "3.9"
services:
  reverse-proxy:
    command:
      # Use docker as provider
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable web UI
      - --api
      # More verbose log messages
      - --log.level=DEBUG

  backend:
    # Listen for code changes
    command: /start-reload.sh
    volumes:
      # Live mount to make code update live in container
      - ./app:/app
