version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      # Use docker as provider
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable web UI
      - --api
    ports:
      - "80:80"
    volumes:
      # Listen to docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_API_USER}

  db:
    image: postgres:13.3
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    depends_on:
      - db
    build:
      dockerfile: backend.dockerfile
      context: ./app
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.counter.rule=Host(`api.${DOMAIN_NAME}`)
      - traefik.http.services.counter.loadbalancer.server.port=80
volumes:
  app-db-data:


