version: "3.9"
services:
  reverse-proxy:
    command:
      # More verbose log messages
      - --log.level=DEBUG

  backend:
    volumes:
      # Livo mount code to get instant feedback
      - ./app/app:/app
